name: CI/CD API Docs

on:
  push:
    branches:
      - main

jobs:
  validar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar Spectral
        run: npm install -g @stoplight/spectral-cli

      - name: Validar OpenAPI
        run: spectral lint openapi.yaml --ruleset "https://unpkg.com/@stoplight/spectral-rulesets/dist/oas/index.js"

  publicar-docs:
    needs: validar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gerar HTML
        run: |
          npx redoc-cli build openapi.yaml -o index.html

      - name: Publicar GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
